### ISSUE TITLE
Panel Styling

### ISSUE THREAD

**Issue by srk289** [PredixDev/px-datetime-range-panel#2]
Is there a way to style the panel? Few of the styling options should be exposed to parent elements
- Fonts/size
- Selected date background color
- Selected date background radius
- Hover state for both selected/unselected dates

**Comment by benoitjchevalier** [comment]
We can expose more css mixins for customization, I'll forward so this can be prioritized.
In the meantime we're always happy to take on pull requests ;)

The last three options would probably be css mixins in px-calendar-picker

**Comment by randyaskin** [comment]
FYI the second one will have been exposed as a style variable in the theming effort currently underway. I'm not sure how much beyond colors we plan to expose as mixins, as things will start to diverge and look less-and-less like Predix UI components.

**Comment by randyaskin** [comment]
The [px-calendar-picker API](https://www.predix-ui.com/#/components/px-calendar-picker/) has been updated with the style variables for the date backgrounds (hover, pressed, selected, etc), which are inherited by the px-datetime-range-panel. Here's a CodePen showing how to use them (wrap in a custom-style block, either use a selector that targets your component or `:root` to select all in the document) - http://codepen.io/randyaskin/pen/peyPWW?editors=1000
