### ISSUE TITLE
Support minute level ranges in presetRanges

### ISSUE THREAD

**Issue by manderson23** [PredixDev/px-datetime-range-panel#3]
I'd like to have presetRanges such as last 5 minutes and last 15 minutes.

However, this seems to be prevented by use of `_preserveTime` in `_presetSelected`.

**Comment by benoitjchevalier** [comment]
Thanks for bringing this to our attention, looks like a bug to me

**Comment by davidsteinberger** [comment]
I actually don't think this is caused by `_preserveTime`. Isn't it, that _px-datetime-range-panel.html_ copies `fromMoment` (and `toMoment`) instead of setting it:

    if(startOk) {
      this.$.from.fromMoment = start.clone();
      this.$.to.fromMoment = start.clone();

      // preserves this.fromMoment into obj returned by start.clone()
      this.set('fromMoment', this._preserveTime(this.fromMoment, start.clone()));
    }

@benoitjchevalier Can u confirm?

**Comment by randyaskin** [comment]
Added in v1.0.0.
