### ISSUE TITLE
Getting Uncaught error when I include the px-datetime-range-panel

### ISSUE THREAD

**Issue by Ishank-dubey** [PredixDev/px-datetime-range-panel#6]
I am working with the PX Seed App.
I have included-  
```
<link 
rel="import" 
href="../../bower_components/px-datetime-range-panel/px-datetime-range-panel.html">
```
in my component and then giving -
```
<px-datetime-range-panel
 time-format="hh:mm:ss A" 
 block-future-dates="true" 
 time-zone="UTC">
 </px-datetime-range-panel>
```
in my local dom. I am getting this error- 
![calerror](https://cloud.githubusercontent.com/assets/1701231/22198580/20a34c6c-e17d-11e6-83b7-5520adc3fc95.PNG)

**Comment by Ishank-dubey** [comment]
some how the `module.exports?` returns true and the program enters the `require('monent')` so replaced old one with `module.exports=b(a.moment):b(a.moment)` to resolve the error. What could be the reason for that, is it related to the gulp task somehow?

**Comment by gedesigntech** [comment]
Hi, glad you have resolved the issue.
The fix seems to be in a library outside of Predix code.  Consider letting the code owner know and submitting a pull request.  Thanks!
